### PR TITLE
Fix jsx and tsx files often detected as html

### PR DESCRIPTION
**Pull request by knu**

### CODE REVIEW

**Comment by wofr06** [comment]
Why is the code for changing the ftype not placed further below (around line 140 where text only formats are handled)? What is the reason for setting ftype to jsx or jsx-...? Many colorizers recognize the js file type, but not your choices. Would the colorizers do a bad job for setting ftype to js?

**Comment by knu** [comment]
@wofr06 That section is inside the `if [[ "$fcat" == application && "$ftype" == octet-stream || "$fcat" == text && $ftype == plain ]]` block and thus not reached when a jsx/tsx file is mistaken as text/html.  Answering to the second question, HTML files are treated specially in isfinal() and are not passed to a colorizer but to a browser instead.

**Comment by wofr06** [comment]
Place inside less pipe is agreed. For me the output is colored with your patch when using bat/batcat, but colored differently for type js. For other colorizers only js produces colored output. I let you decide whether ftype js is appropriate.

01.10.2023 23:05:13 Akinori MUSHA ***@***.***>:

**Comment by knu** [comment]
You're right, I'm using bat.  I think it's mostly "OK" to view a jsx/tsx file colorized as a js file, but it definitely looks nicer when viewing it with bat which has direct support for jsx and tsx.

**Pull request merged**
