### PR TITLE
use bat's default setting

### PR DESCRIPTION
**Pull request by Freed-Wu**
If use specify `LESSCOLORIZER='bat --style=XXX'`, add `--style=XXX` to opt.
On the contrast, don't specify `--style` in order to use bat's default setting.
that is:
1. if `$BAT_STYLE` exist, use it
2. use bat's config file.

### CODE REVIEW

**Comment by Freed-Wu** [comment]
<https://github.com/wofr06/lesspipe/blob/lesspipe/lesspipe.sh#L405> is not used because whatever `$prog`, `$opt` will be reset.

```sh
	[[ "$2" =~ ^[0-9]*$ || -z "$2" ]] && opt=() || opt=(-l "$2")
	case $prog in
		bat|batcat)
			# only allow an explicitly requested language
			[[ -z $3 ]] && opt=() || opt=(-l "$3")
		pygmentize)
			pygmentize -l "$2" /dev/null &>/dev/null && opt=(-l "$2") || opt=(-g)
		source-highlight)
			[[ -n "${opt[*]}" && -n "$2" ]] && opt=(-s "$2") || opt=()
		code2color|vimcolor)
			opt=("$1")
		*)
			return ;;
	esac
```

**Comment by Freed-Wu** [comment]
```sh
			pygmentize -l "$2" /dev/null &>/dev/null && opt=(-l "$2") || opt=(-g)
```

For `bat`, it still need a detection to judge if the language is supported.

**Comment by Freed-Wu** [comment]
`$fext` is same as `$file2`, so why we must pass both of them?

```sh
		[[ -n "$file2" ]] && fext="$file2"
		[[ -z ${colorizer[*]} ]] && has_colorizer "$1" "$fext" "$file2"
```

**Comment by Freed-Wu** [comment]
```sh
	[[ $lang == plain || -z $lang ]] && return
```

It make it is impossible to use bat to display line number for plain text.

**Comment by Freed-Wu** [comment]
How about name some variable? `$1`, `$2` is too hard to understand its function. Like

```sh
  filename=$1
	lang=$2
```

**Comment by wofr06** [comment]
Done differently by checking the config file

**Pull request closed without merging**
